repos:
-   repo: local
    hooks:
    - id: jupytext
      name: jupytext
      entry: jupytext --to md
      files: .ipynb
      language: python
    - id: stage-md
      name: stage-md
      entry: git add **/*.md
      language: system
